# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 6 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-pr-stale: 50
        days-before-issue-stale: 50
        stale-pr-label: 'stale'
        stale-issue-label: 'stale'
        exempt-pr-labels: keep-open
        exempt-issue-labels: keep-open
        stale-pr-message: >
          This pull request has been inactive for at least 50 days.
          If you are finished with your changes, don't forget to merge.
        stale-issue-message: >
          This issue has been inactive for at least 50 days.